### ISSUE TITLE
Plotting the doppeling time

### ISSUE THREAD

**Issue by TakeItAndRun** [valeriupredoi/COVID-19_LINEAR#2] opened 2020-03-17 18:22 UTC
Would it be possible to plot the doubling time as a function of time.
Using always the last X days for the exponential regression. This would really show the efficiency of containment effects.
How to choose X?
In this paper:

https://annals.org/aim/fullarticle/2762808/incubation-period-coronavirus-disease-2019-covid-19-from-publicly-reported

they plot the Cumulative distribution function of the COVID-19 incubation:

![Incubation period](https://user-images.githubusercontent.com/1910540/76887744-ff827b80-6882-11ea-9402-80f9bd82ad04.jpeg)

"The estimated median incubation period of COVID-19 was 5.1 days (CI, 4.5 to 5.8 days). We estimated that fewer than 2.5% of infected persons will display symptoms within 2.2 days (CI, 1.8 to 2.9 days) of exposure, whereas symptom onset will occur within 11.5 days (CI, 8.2 to 15.6 days) for 97.5% of infected persons."

So I would initially choose X=5.

I think this data also means that any change of the containment of the corona virus would only been seen after about the median incubation period later in the data?

**Comment by valeriupredoi** [comment] 2020-03-17 18:37
yeah good call! I suspect the containment will show up like you say, on average, after x=incubation time - it's quite visible in China
![2019-ncov_lin_02-02-2020](https://user-images.githubusercontent.com/28983971/76889816-31ddaa00-687e-11ea-94c6-4f7abb7bc8d7.png)
Quarantine started January 23rd and you can see a visible slowdown January 27.
I'll have a stab at plugging in the doubling time tomorrow, cheers for the suggestion :beer:

**Comment by valeriupredoi** [comment] 2020-03-18 14:12
I have now started the automated recording of the daily mean (over 12 countries) doubling time in [this file](https://github.com/valeriupredoi/COVID-19_LINEAR/blob/master/country_data/mean_doubling_time) - I am interested in seeing a decrease over time suggesting the effect of local quarantines (this does not include the UK since there is no actual quarantine instated here just yet sigh). Hopefully we'll see a noticeable change in a couple weeks :+1:

**Comment by TakeItAndRun** [comment] 2020-03-19 10:30
Are you starting all your plots on the March 1th?
As time goes on your range gets longer and longer.
If there are changes in the rise over time, than the quality of your fits should be getting poorer and poorer.
- - - - - - 
There might be a way to find the best range to do the regression over:
Do the regression for the last 2 days.
Then do the regression for  one day longer each.
Pick the regression with the best fit (R closest to one)

**Comment by valeriupredoi** [comment] 2020-03-19 12:50
yeah good call! I have now changed to two regressions for select countries that show slowdowns in the past few days; I can always run an MCMC to find the curve parameters but I must do my day job (from home) so not much time to implement it :cry:

**Comment by TakeItAndRun** [comment] 2020-03-19 15:05
Nice work.
It would be so valuable to get your work out there to make people see that/which measures are effective and necessary.

**Comment by valeriupredoi** [comment] 2020-04-19 11:36
cheers! am gonna close this since all is now documented, have a look at https://valeriupredoi.github.io/ and stay safe and have a good weekend! :beer:

**Closed as completed by valeriupredoi** 2020-04-19 11:36 UTC
